include:
  - board: nrf52840dk_nrf52840
    shield: le_jlwffre
    keymap: config/le_jlwffre.keymap
    shield_dir: config/boards/shields/le_jlwffre
    extra_args:
      - -DCONFIG_BUILD_OUTPUT_UF2=y
      - -DCONFIG_BUILD_OUTPUT_BIN=n
      - -DCONFIG_BUILD_OUTPUT_HEX=n
      - -DCONFIG_BUILD_OUTPUT_UF2_REQUIRED=y
      - -DCONFIG_USB=y
      - -DCONFIG_USB_DEVICE_STACK=y
      - -DCONFIG_USB_DEVICE_HID=y
