manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: youknowfred
      url-base: https://github.com/youknowfred
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Add the name of the repository as a project.
    - name: jlw-zmk-config
      remote: youknowfred
      revision: main
  self:
    path: config
