manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: youknowfred
      url-base: https://github.com/youknowfred
    - name: jlw-keyboards
      url-base: https://github.com/josh-l-wang
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 3c2a91d5a5b0c5a6b1d1a5b0c5a6b1d1a5b0c5a6
      import: app/west.yml
    - name: jlw-zmk-config
      remote: youknowfred
      revision: main
    - name: zmk-jlw-keyboards
      remote: jlw-keyboards
      revision: main
  self:
    path: config
