on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update --narrow -o=--depth=1

      - name: West Zephyr export
        run: west zephyr-export

      - name: Configure West
        run: |
          west config build.board_warn false
          west config build.board nrf52840dk_nrf52840
          echo "BOARD=nrf52840dk_nrf52840" >> $GITHUB_ENV

      - name: West Clean
        run: west build -p -t clean -s zmk/app -b nrf52840dk_nrf52840

      - name: West Build (le_jlwffre)
        env:
          BOARD: nrf52840dk_nrf52840
        run: |
          west build -p -s zmk/app -- \
            -DBOARD=nrf52840dk_nrf52840 \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" \
            -DSHIELD=le_jlwffre \
            -DSHIELD_DIR="${GITHUB_WORKSPACE}/config/boards/shields/le_jlwffre" \
            -DKEYMAP_FILE="${GITHUB_WORKSPACE}/config/le_jlwffre.keymap" \
            -DCONF_FILE="${GITHUB_WORKSPACE}/config/le_jlwffre.conf" \
            -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Rename artifacts
        if: success()
        run: |
          mkdir -p artifacts
          if [ -f build/zephyr/zmk.uf2 ]; then
            cp build/zephyr/zmk.uf2 artifacts/le_jlwffre.uf2
          fi

      - name: Archive firmware
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/
          retention-days: 90
