on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update --narrow -o=--depth=1

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Clean
        run: west build -p -t clean -s zmk/app

      - name: West Build (le_jlwffre)
        run: |
          west build -p -s zmk/app -b nrf52840dk_nrf52840 -- \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" \
            -DSHIELD=le_jlwffre \
            -DCONF_FILE="${GITHUB_WORKSPACE}/config/le_jlwffre.conf" \
            -DCONFIG_ZMK_BOARD_LE_JLWFFRE=y \
            -DCONFIG_ZMK_SHIELD_LE_JLWFFRE=y \
            -DCONFIG_ZMK_USB=y \
            -DCONFIG_ZMK_USB_PRODUCT="le_jlwffre" \
            -DCONFIG_ZMK_UART_CONSOLE=y \
            -DCONFIG_ZMK_UART_CONSOLE_UART0=y \
            -DCONFIG_ZMK_BLE=y \
            -DCONFIG_ZMK_BLE_DEVICE_NAME="le_jlwffre" \
            -DCONFIG_BUILD_OUTPUT_UF2=y \
            -DCONFIG_BUILD_OUTPUT_BIN=n \
            -DCONFIG_BUILD_OUTPUT_HEX=n \
            -DCONFIG_BUILD_OUTPUT_UF2_REQUIRED=y \
            -DZMK_CONFIG_DEBUG_INIT=y

      - name: Rename artifacts
        if: success()
        run: |
          mkdir -p artifacts
          if [ -f build/zephyr/zmk.uf2 ]; then
            cp build/zephyr/zmk.uf2 artifacts/le_jlwffre.uf2
          fi

      - name: Archive firmware
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/
          retention-days: 90
